"""create initial schema

Revision ID: e3b118921749
Revises: 
Create Date: 2026-07-01 23:04:52.028278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b118921749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body_type', sa.Enum('HATCHBACK', 'SEDAN', 'SUV', 'MUV', 'COUPE', 'CONVERTIBLE', 'PICKUP', name='body_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maker_id'], ['makers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maker_id', 'name', name='uq_car_models_maker_id_name')
    )
    op.create_index(op.f('ix_car_models_body_type'), 'car_models', ['body_type'], unique=False)
    op.create_table('car_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'CNG', 'ELECTRIC', 'HYBRID', name='fuel_type_enum'), nullable=False),
    sa.Column('transmission_type', sa.Enum('MANUAL', 'AUTOMATIC', 'AMT', 'CVT', 'DCT', name='transmission_type_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_car_variants_price_positive'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'name', name='uq_car_variants_model_id_name')
    )
    op.create_index(op.f('ix_car_variants_fuel_type'), 'car_variants', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_car_variants_price'), 'car_variants', ['price'], unique=False)
    op.create_index(op.f('ix_car_variants_transmission_type'), 'car_variants', ['transmission_type'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_model_id'), 'reviews', ['model_id'], unique=False)
    op.create_table('variant_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['car_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'feature_id', name='uq_variant_features_variant_id_feature_id')
    )
    op.create_index(op.f('ix_variant_features_feature_id'), 'variant_features', ['feature_id'], unique=False)
    op.create_table('variant_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('engine_displacement_cc', sa.Integer(), nullable=True),
    sa.Column('power_bhp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('torque_nm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mileage_kmpl', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seating_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('wheelbase_mm', sa.Integer(), nullable=True),
    sa.Column('boot_space_litres', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_capacity_litres', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ground_clearance_mm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('boot_space_litres > 0', name='ck_variant_specs_boot_space_positive'),
    sa.CheckConstraint('engine_displacement_cc > 0', name='ck_variant_specs_displacement_positive'),
    sa.CheckConstraint('fuel_tank_capacity_litres > 0', name='ck_variant_specs_fuel_tank_positive'),
    sa.CheckConstraint('ground_clearance_mm > 0', name='ck_variant_specs_ground_clearance_positive'),
    sa.CheckConstraint('height_mm > 0', name='ck_variant_specs_height_positive'),
    sa.CheckConstraint('length_mm > 0', name='ck_variant_specs_length_positive'),
    sa.CheckConstraint('mileage_kmpl > 0', name='ck_variant_specs_mileage_positive'),
    sa.CheckConstraint('power_bhp > 0', name='ck_variant_specs_power_positive'),
    sa.CheckConstraint('seating_capacity > 0', name='ck_variant_specs_seating_positive'),
    sa.CheckConstraint('torque_nm > 0', name='ck_variant_specs_torque_positive'),
    sa.CheckConstraint('wheelbase_mm > 0', name='ck_variant_specs_wheelbase_positive'),
    sa.CheckConstraint('width_mm > 0', name='ck_variant_specs_width_positive'),
    sa.ForeignKeyConstraint(['variant_id'], ['car_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_specifications')
    op.drop_index(op.f('ix_variant_features_feature_id'), table_name='variant_features')
    op.drop_table('variant_features')
    op.drop_index(op.f('ix_reviews_model_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_car_variants_transmission_type'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_price'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_fuel_type'), table_name='car_variants')
    op.drop_table('car_variants')
    op.drop_index(op.f('ix_car_models_body_type'), table_name='car_models')
    op.drop_table('car_models')
    op.drop_table('makers')
    op.drop_table('features')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop Postgres ENUM types on its own -- do it explicitly
    # so downgrade fully reverses the upgrade instead of leaving orphaned types.
    sa.Enum(name='fuel_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transmission_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='body_type_enum').drop(op.get_bind(), checkfirst=True)
